### ISSUE TITLE
app.i-mas.ml과 점수 차이 질문입니다

### ISSUE THREAD

**Issue by jasonhahm** [HyphenK/mltdkei_v3#1]
안녕하세요, 이전 버전부터 계산기 잘 쓰고 있는 사람입니다.

app.i-mas.ml 과 점수 차이가 조금 있는 것 같은데 혹시 교차검증 해보셨나요?

이번 이벤트 곡 계산 결과인데 일정한 차이가 있는것을 보니 시행횟수의 차이 때문도 아닌 것 같아서 여쭤봅니다.

![2](https://user-images.githubusercontent.com/9298725/126855222-3fb334c1-4d31-414a-b838-5d721d29fd3a.png)

![3](https://user-images.githubusercontent.com/9298725/126855226-d45f8394-2bb5-4f46-926f-edbda66fbfac.png)

**Comment by jasonhahm** [comment]
추가로 현재 덱당 시행횟수 제한이 20000인 것으로 보이는데 맞다면 혹시 더 늘려주실 수 있으신가요?

아래는 지금 막 다시 계산해본 결과입니다.

![5](https://user-images.githubusercontent.com/9298725/126855444-0568d7e0-ff5a-41dc-b3ed-486912130831.png)

**Comment by HyphenK** [comment]
Ideal 점수를 제외하면 모두 확률이 계산에 들어가기 때문에 발생하는 문제입니다. 특히 상위 퍼센트에 가까울수록 그에 해당하는 표본이 적어지기에(Ex: 2만번 시뮬레이션 돌리면 0.1% 점수는 20000×0.001×2=40개 결과의 평균값으로 계산) 오차가 비교적 크게 튀는 경향이 있습니다.

**Comment by jasonhahm** [comment]
평균값으로 계산하는거였군요. 저는 0.1% 백분율에 해당되는 부분의 점수를 가져오는 방식인 줄 알았네요. 평균을 낸다면 점수가 더 올라가지 않을까요?
그런데 혹시 Ideal 스코어는 왜 차이가 나는걸까요

**Comment by HyphenK** [comment]
한 3.1 버전까지는 그렇게 했었는데, 그렇게 했더니 점수 출렁임도 너무 심하고 지나치게 낮은 값이 나오는 문제도 있어서 평균값 방식을 사용하고 있습니다.
Ideal 점수는 소숫점 계산 오차가 모여서 차이가 커진 게 아닐까 싶기는 한데, 자세한 건 저도 뜯어봐야 해서 지금은 잘 모르겠습니다.

**Comment by jasonhahm** [comment]
답변 감사합니다.
평균값 건은 저도 정답이 있는 문제는 아닌 것 같네요.
애초에 확률이 개입되는 문제이고 계산값은 참고만 되면 충분하니까요.
각 분위별 점수들의 차이만 정상적이라면 문제는 없을 것 같습니다.

근데 만약 Ideal Score 부분이 계산식의 오차 문제라면, 해결되었을 때 분위별 점수들도 조금씩 내려갈지도 모르겠네요.

항상 꾸준히 업데이트 해주셔서 감사합니다.

**Comment by HyphenK** [comment]
그리고 덱당 시행횟수를 늘리는 것 자체는 어려운 일은 아니지만, 시간이 너무 오래 걸린다는 문제가 있어서 아직 2만번 수준에서 제한을 걸고 있습니다. 간단히 설명드리자면, 저 웹버전 계산기는 1개 덱에 대해서만 계산하는 거라 시행횟수를 늘리는 데에 부담이 적지만, 제 계산기는 50개 덱에 대해 2만번 계산을 돌린다고만 해도 100만번 계산을 돌리는 꼴이 됩니다.

**Comment by jasonhahm** [comment]
네, 덱이 많아서 오래 걸리는 점은 저도 이해합니다.
제가 조금 더 걸리더라도 최대한 근접한 점수를 보고 싶어서 말씀드렸습니다.
근데 사실 2만번만 해도 5만번 했을때와 비해 큰 오차가 나는것도 아니라서 그건 괜찮을 것 같아요
