### ISSUE TITLE
오류 관련 제보

### ISSUE THREAD

**Issue by million765** [HyphenK/mltdkei_v3#2]
![image](https://user-images.githubusercontent.com/88002352/127048920-2b722c68-a20d-4a71-a385-3ed157e3043a.png)

덱모드에서 송타입/프린세스/페어리/엔젤 을 선택한 후 계산기를 돌리면 아무것도 뜨지 않는 현상이 발생합니다.
3속성과 올타입은 맞게 돌아갑니다.
확인 부탁드립니다.

**Comment by HyphenK** [comment]
확인 결과 프로그램상 버그는 아니고, 계산 설정 문제인 것으로 보입니다. 프리셋을 Ranker로 설정하여 다시 시도해 보시면 정상 작동할 것으로 예상됩니다.

**Comment by HyphenK** [comment]
혹시 프리셋 설정 변경 이후에도 증상이 지속될 경우, mltdkei_info.txt 혹은 mltdkei_info_kr.txt 파일을 hyphen131@naver.com 으로 보내주시면 해당 파일을 이용해 버그 유무를 다시 한 번 확인해드리겠습니다.

**Comment by million765** [comment]
메일 보내드렸습니다. 확인 부탁드립니다.

**Comment by HyphenK** [comment]
확인 결과, 뭐라도 떠야 하는데 아예 안 뜨는 걸 보니 프로그램 측 버그가 맞는 것 같습니다. 다행히 대강 어디가 문제겠구나 싶은 부분이 있어서, 다음 버전에서 수정하겠습니다.
지금 당장 프로그램을 사용하셔야 한다면, SR 등급 카드도 프로그램에 추가해 놓으시면 임시로 해결이 가능할 것 같습니다. (서포트 편성에 스알 카드가 사용되는 경우가 있어서, 점수 정확도도 높아집니다.)
추가로 점수는 FC일 때를 기준으로 계산되기에, 콤보가 자주 끊어지거나 그렛이 많다거나(20% 이상) 하면 50% 점수보다도 낮은 점수가 나올 수 있습니다.

**Comment by million765** [comment]
답변 감사드립니다. 더위 조심하시길 바랍니다🙂
