### ISSUE TITLE
config idol list에서 16열이 아닌 14열만 나옵니다

### ISSUE THREAD

**Issue by mwvg** [HyphenK/mltdkei_v3#3]
<img width="909" alt="제목 없음" src="https://user-images.githubusercontent.com/23013357/127793976-bafb0b9f-c65c-444f-b84b-51901312e97c.png">

window10 이용중이고, 노트북입니다. 디스플레이 해상도가 달라 생긴 문제인가 해서 다른 해상도로 다 바꿔봐도 14열만 나오고, 옆으로 이동하는 바도 뜨지않아 오른쪽 2열은 체크할 수가 없네요. 도움 부탁드립니다.

**Comment by HyphenK** [comment]
혹시 이쪽 참고해서 글자 크기를 작게 해 봐도 같은 증상 나타나나요?

https://support.microsoft.com/ko-kr/windows/windows-10%EC%9D%98-%ED%85%8D%EC%8A%A4%ED%8A%B8-%ED%81%AC%EA%B8%B0-%EB%B3%80%EA%B2%BD-1d5830c3-eee3-8eaa-836b-abcc37d99b9a

**Comment by mwvg** [comment]
글자 크기 문제였군요 이제 잘 나옵니다 감사합니다
