### ISSUE TITLE
버그인지 뭔진 정확힌 모르겠으나 작동이 안됩니다

### ISSUE THREAD

**Issue by milboong2** [HyphenK/mltdkei_v3#5]
그제 처음 설치해서 제대로 됐는데 어제 신곡 나온 이후 업뎃을 눌렀더니 음악 업뎃은 괜찮고 카드 업뎃에서 complete 뜬 이후에 checking mltdkei_info.txt updates라고 뜨면서 시간 단위로 기다려도 안넘어가고 계산기의 config idol list가 info 파일이 손상됐거나 업뎃이 안됐다면서 작동이 안됩니다. 문제는 다 삭제하고 재설치해봐도 이런다는 건데 원래 저 checking 부분이 몇시간동안 진행되는건가요? 아니면 뭔가 문제가 있는건가요?

**Comment by HyphenK** [comment]
뭔가 문제가 있는 거 같네요. 조사 좀 해보고 뭐가 문제인지 알려드리겠습니다.

**Comment by milboong2** [comment]
> 뭔가 문제가 있는 거 같네요. 조사 좀 해보고 뭐가 문제인지 알려드리겠습니다.

네 알겠습니다

**Comment by HyphenK** [comment]
제가 가지고 있는 샘플로는 버그 재현이 안 되는 것 같습니다. 괜찮으시다면 mltdkei_info.txt 파일을 hyphen131@naver.com 으로 보내주시면 해당 파일 검토 후 뭐가 원인인지 알려드리겠습니다.

**Comment by HyphenK** [comment]
샘플 파일 문제가 아니었네요. 버그 원인을 발견하여 현재 수정 작업 중입니다.

**Comment by HyphenK** [comment]
일단 구동은 가능하게 임시로 만든 파일을 올려두었습니다. mltdkei_v421.exe 파일을 Release 4.2 에서 받아 사용해주세요.

**Comment by milboong2** [comment]
감사합니다 연휴 마지막날 잘 보내세요
+checking 멈춤 없이 진행되고 카드목록도 현재로선 정상적으로 들어가지네요

**Comment by HyphenK** [comment]
exe 버전에 한해 수정된 4.22 업데이트 릴리즈 완료.
