### ISSUE TITLE
안녕하세요 선생님 문제가 생긴듯 합니다

### ISSUE THREAD

**Issue by milboong2** [HyphenK/mltdkei_v3#6]
그동안 잘 쓰다가 이벤 새로 시작 하면서 카드 업뎃 하는데 아리사 신 sr부분에서 업데이트가 멈추네요
확인해주시면 감사하겠습니다

**Comment by HyphenK** [comment]
잠시만 기다려주세요. 원인 자체는 찾았는데 그걸 고쳤더니 에러가 이곳저곳에서 터져나오고 있어서 시간이 좀 걸릴 거 같습니다.

**Comment by HyphenK** [comment]
수정된 4.24 버전 업로드 되었습니다.
